### PR TITLE
Fleisher white button variants

### PR DESCRIPTION
**Pull request by YSNIS**

### CODE REVIEW

**Comment by vishakha94** [comment]
@YSNIS Thanks for the PR.
- Can you pls make sure that the tests are passing? 
- Add sample screenshots of button variations?

**Comment by vishakha94** [comment]
@YSNIS PR LGTM.
Just a question regarding the button's border. Have these buttons been tested on non-white backgrounds? I am slightly concerned about how would they look on really dark backgrounds where the black border could end up looking odd.

**Comment by bluepnume** [comment]
Hi,

I didn't see any tests included in this PR. Can you please make sure there's at least:

- A test in `validation.js` to make sure `white` is recognized as a valid button color
- Any screenshots generated in `test/screenshot/images` are checked into github

**Comment by YSNIS** [comment]
Will do.  Working on those now.

**Comment by vishakha94** [comment]
@YSNIS ANy update for test in `validations.js`?
FYI: we have already checked in screenshots for the white button.

**Comment by mcntsh** [comment]
@YSNIS I created a PR for those snapshots but it seems like some of the snapshots were blank. I'd double check the configuration.

https://github.com/paypal/paypal-checkout/pull/807

**Comment by abarco** [comment]
@YSNIS Your PR (https://github.com/paypal/paypal-checkout/pull/811) was reverted for not having snapshot tests and failing. Please run `npm run test` and verify that all your renderings are in order.

**Pull request merged**
