### PR TITLE
[WIP]Add Karma and webpack debugging

### PR DESCRIPTION
**Pull request by trainerbill**
If you don't have gulp-cli you have to run
```
npm install -g gulp-cli
```

1.  gulp 4
2.  Reworked all gulp tasks
3.  Added build:watch to quickly rebuild
4.  Separated to tasks folder to reduce gulpfile clutter
5.  Fixed a Karma issue.
6.  Added debug argument

### CODE REVIEW

**Comment by bluepnume** [comment]
Let's expose this as a command line argument? `--debug` ?

**Comment by bluepnume** [comment]
Can use `yargs.argv['debug']`

**Comment by trainerbill** [comment]
so --karma-debug and --webpack-debug?

**Comment by bluepnume** [comment]
Works for me if you need that granularity, otherwise we could just lump them under a single flag.

**Comment by trainerbill** [comment]
@bluepnume Ready for an initial review.  I need you to check that the files are building properly, specifically the values in the DefinePlugin.

**Comment by bluepnume** [comment]
Gonna close this for now as many of these changes were merged. If you wanna add a separate PR for gulp 4 that's cool.

**Pull request closed without merging**
