### PR TITLE
chore(venmo-blacklist): Blacklisting chick-fil-a from venmo

### PR DESCRIPTION
**Pull request by mcntsh**

### CODE REVIEW

**Comment by JelisaCooper** [comment]
Original Auto Salez

**Comment by JelisaCooper** [comment]
Original Auto Salez

**Review by JelisaCooper — COMMENTED** [review]
Original Auto Salez

**Comment by Only1adhd228** [comment]
1146caa0d47aaf70b1cf50be0175ec91babbd2b1

**Pull request merged**
