### PR TITLE
Upgrade to webpack 3 with scope hoisting

### PR DESCRIPTION
**Pull request by trainerbill**
Scope hoisting... yay.

https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

The __IE_POPUP_SUPPORT__ flag and the lib UMD build are failing due to an issue with post-robots Promise export.  Is the UMD build even needed?  I commented out the configurations that are failing in webpack.conf.js

```
Cannot get final name for export "Promise" in "./node_modules/post-robot/src/lib/index.js" (known exports: true, known reexports: promiseMap once noop safeHasProp safeGetProp listen apply find map some keys values getByValue uniqueID memoize extend each replaceObject safeInterval intervalTimeout getDomainFromUrl safeGet isRegex weakMapMemoize getWindowType jsonStringify jsonParse log listenForMethods serializeMethod serializeMethods deserializeMethod deserializeError deserializeMethods initOnReady onWindowReady)
Error: Cannot get final name for export "Promise" in "./node_modules/post-robot/src/lib/index.js" (known exports: true, known reexports: promiseMap once noop safeHasProp safeGetProp listen apply find map some keys values getByValue uniqueID memoize extend each replaceObject safeInterval intervalTimeout getDomainFromUrl safeGet isRegex weakMapMemoize getWindowType jsonStringify jsonParse log listenForMethods serializeMethod serializeMethods deserializeMethod deserializeError deserializeMethods initOnReady onWindowReady)
    at getFinalName (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:49:8)
    at getFinalName (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:34:11)
    at info.globalScope.through.forEach.reference (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:382:24)
    at Array.forEach (native)
    at modulesWithInfo.forEach.info (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:370:29)
    at Array.forEach (native)
    at ConcatenatedModule.source (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:369:19)
    at ModuleTemplate.render (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/ModuleTemplate.js:14:31)
    at /home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Template.js:110:28
    at Function.from (native)
    at Chunk.mapModules (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Chunk.js:159:16)
    at MainTemplate.renderChunkModules (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Template.js:107:26)
    at MainTemplate.plugin (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/MainTemplate.js:44:25)
    at MainTemplate.applyPluginsWaterfall (/home/athroener/vscode/paypal-checkout/node_modules/tapable/lib/Tapable.js:91:24)
    at MainTemplate.render (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/MainTemplate.js:178:21)
    at Compilation.createChunkAssets (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Compilation.js:1255:34)]
  message: 'chunk main [entry]\ncheckout.v4.js\nCannot get final name for export "Promise" in "./node_modules/post-robot/src/lib/index.js" (known exports: true, known reexports: promiseMap once noop safeHasProp safeGetProp listen apply find map some keys values getByValue uniqueID memoize extend each replaceObject safeInterval intervalTimeout getDomainFromUrl safeGet isRegex weakMapMemoize getWindowType jsonStringify jsonParse log listenForMethods serializeMethod serializeMethods deserializeMethod deserializeError deserializeMethods initOnReady onWindowReady)\nError: Cannot get final name for export "Promise" in "./node_modules/post-robot/src/lib/index.js" (known exports: true, known reexports: promiseMap once noop safeHasProp safeGetProp listen apply find map some keys values getByValue uniqueID memoize extend each replaceObject safeInterval intervalTimeout getDomainFromUrl safeGet isRegex weakMapMemoize getWindowType jsonStringify jsonParse log listenForMethods serializeMethod serializeMethods deserializeMethod deserializeError deserializeMethods initOnReady onWindowReady)\n    at getFinalName (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:49:8)\n    at getFinalName (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:34:11)\n    at info.globalScope.through.forEach.reference (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:382:24)\n    at Array.forEach (native)\n    at modulesWithInfo.forEach.info (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:370:29)\n    at Array.forEach (native)\n    at ConcatenatedModule.source (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/optimize/ConcatenatedModule.js:369:19)\n    at ModuleTemplate.render (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/ModuleTemplate.js:14:31)\n    at /home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Template.js:110:28\n    at Function.from (native)\n    at Chunk.mapModules (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Chunk.js:159:16)\n    at MainTemplate.renderChunkModules (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Template.js:107:26)\n    at MainTemplate.plugin (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/MainTemplate.js:44:25)\n    at MainTemplate.applyPluginsWaterfall (/home/athroener/vscode/paypal-checkout/node_modules/tapable/lib/Tapable.js:91:24)\n    at MainTemplate.render (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/MainTemplate.js:178:21)\n    at Compilation.createChunkAssets (/home/athroener/vscode/paypal-checkout/node_modules/webpack/lib/Compilation.js:1255:34)',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
```

### CODE REVIEW

**Comment by bluepnume** [comment]
This is awesome!

UMD build is needed for people who are using the npm module and webpacking/requirejs'ing us.

"Cannot get final name for export" -- I think I see the issue here. Let me add a fix to post-robot

**Comment by bluepnume** [comment]
OK please try with the latest post-robot

**Comment by trainerbill** [comment]
Cannot get final name for export "util" in "./node_modules/post-robot/src/lib/util.js"

**Comment by bluepnume** [comment]
Fixed again. I just tried your changes though, and I don't see a whole lot of changes in `dist/checkout.js`...

**Comment by bluepnume** [comment]
Definitely doing something though, it cuts 6kb off the build!

**Comment by bluepnume** [comment]
If you can uncomment those lines I'll gladly merge this 👍

**Comment by trainerbill** [comment]
done!

**Pull request merged**
