### PR TITLE
Dockerize and document demo app

### PR DESCRIPTION
**Pull request by ErikMHummel**
This adds Docker support for the demo app to make it easy to standup locally.

This needs an update to documentation to describe how to use it. I am not sure the right place though.  So please let me know where that should be and I will update this PR with that for full submission.

### CODE REVIEW

**Comment by bluepnume** [comment]
Yeah, this repo is a good place to keep docs centralized. Could you add something to the docs/ folder?

**Comment by bluepnume** [comment]
Looks good! I think you may have picked up one of my commits (I did a force push to remove some commented tests and thought I'd gotten away with it) but otherwise looks good to me!

**Comment by ErikMHummel** [comment]
@bluepnume I have added a demo-app.md in the docs folder with as much as I know about the app.  I also updated the Dockerfile to be more fully self-contained.

Please let me know if you want anything else changed.

PS. I think I may have messed up a merge as I have a few of your changes here.

**Comment by bluepnume** [comment]
Yeah naw it's my fault. But if you could just remove the commented tests that got inlined in your PR, that would be awesome. When I merge, it'll squash and clean up the history.

**Comment by ErikMHummel** [comment]
Done.

**Comment by bluepnume** [comment]
Awesome! Thanks for adding this, merging

**Pull request merged**
